name: "Compile Mix Assets"

on:
  pull_request:
    branches: [ "main", "master", "release/**" ]

permissions:
  contents: write

jobs:
  mix-asset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Compile Production Assets
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install --force
      - run: npm run prod

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build: compiled mix assets release"